//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminBooking()
        {
            this.AdminPayments = new HashSet<AdminPayment>();
        }
    
        public int BookingId { get; set; }
        public string Username { get; set; }
        public int EventId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> TicketsBooked { get; set; }
        public Nullable<int> TicketPrice { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual OrganiserEvent OrganiserEvent { get; set; }
        public virtual OrganiserRegister OrganiserRegister { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminPayment> AdminPayments { get; set; }
    }
}
