//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminFeedback
    {
        public int FeedbackId { get; set; }
        public string Username { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual OrganiserRegister OrganiserRegister { get; set; }
    }
}
