//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminPayment
    {
        public int PaymentId { get; set; }
        public string Username { get; set; }
        public int BookingId { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> Amount { get; set; }
        public string TransactionId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual AdminBooking AdminBooking { get; set; }
        public virtual OrganiserRegister OrganiserRegister { get; set; }
    }
}
