//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliateUserDetail
    {
        public int UserId { get; set; }
        public string AffiliateLinkId { get; set; }
        public string UserName { get; set; }
        public string Gender { get; set; }
        public string EmailId { get; set; }
        public string PhoneNo { get; set; }
        public string City { get; set; }
    
        public virtual AffiliateRegister AffiliateRegister { get; set; }
    }
}
