//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class AffiliateCashOut
    {
        public int CashOutId { get; set; }
        public string EmailId { get; set; }
        public string AffiliateLinkId { get; set; }
        public string AccountHolder { get; set; }
        public string AccountNo { get; set; }
        public string ConfirmAccountNo { get; set; }
        public string IFSC { get; set; }
        public int Amount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TransactionId { get; set; }
    
        public virtual AffiliateRegister AffiliateRegister { get; set; }
    }
}
