//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GtTestEEEntities : DbContext
    {
        public GtTestEEEntities()
            : base("name=GtTestEEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminBooking> AdminBookings { get; set; }
        public virtual DbSet<AdminFeedback> AdminFeedbacks { get; set; }
        public virtual DbSet<AdminLogin> AdminLogins { get; set; }
        public virtual DbSet<AdminPayment> AdminPayments { get; set; }
        public virtual DbSet<AffiliateCashOut> AffiliateCashOuts { get; set; }
        public virtual DbSet<AffiliateContactU> AffiliateContactUs { get; set; }
        public virtual DbSet<AffiliateRegister> AffiliateRegisters { get; set; }
        public virtual DbSet<AffiliateUserDetail> AffiliateUserDetails { get; set; }
        public virtual DbSet<OrganiserBankDetail> OrganiserBankDetails { get; set; }
        public virtual DbSet<OrganiserCategory> OrganiserCategories { get; set; }
        public virtual DbSet<OrganiserContactu> OrganiserContactus { get; set; }
        public virtual DbSet<OrganiserCustomer> OrganiserCustomers { get; set; }
        public virtual DbSet<OrganiserDateTime> OrganiserDateTimes { get; set; }
        public virtual DbSet<OrganiserDiscount> OrganiserDiscounts { get; set; }
        public virtual DbSet<OrganiserEvent> OrganiserEvents { get; set; }
        public virtual DbSet<OrganiserEventCategory> OrganiserEventCategories { get; set; }
        public virtual DbSet<OrganiserEventView> OrganiserEventViews { get; set; }
        public virtual DbSet<OrganiserGSTDetail> OrganiserGSTDetails { get; set; }
        public virtual DbSet<OrganiserImage> OrganiserImages { get; set; }
        public virtual DbSet<OrganiserLead> OrganiserLeads { get; set; }
        public virtual DbSet<OrganiserRegister> OrganiserRegisters { get; set; }
        public virtual DbSet<OrganiserReview> OrganiserReviews { get; set; }
        public virtual DbSet<OrganiserSale> OrganiserSales { get; set; }
        public virtual DbSet<OrganiserSubscription> OrganiserSubscriptions { get; set; }
        public virtual DbSet<OrganiserTax> OrganiserTaxes { get; set; }
        public virtual DbSet<OrganiserTeam> OrganiserTeams { get; set; }
        public virtual DbSet<OrganiserVenue> OrganiserVenues { get; set; }
        public virtual DbSet<UserContact> UserContacts { get; set; }
        public virtual DbSet<UserCorporate> UserCorporates { get; set; }
        public virtual DbSet<UserLike> UserLikes { get; set; }
        public virtual DbSet<UserRegister> UserRegisters { get; set; }
        public virtual DbSet<UserShare> UserShares { get; set; }
        public virtual DbSet<UserSubscribe> UserSubscribes { get; set; }
        public virtual DbSet<UserView> UserViews { get; set; }
    }
}
