//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganiserCustomer
    {
        public string Username { get; set; }
        public int EventId { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Amount { get; set; }
        public string Transact { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual OrganiserEvent OrganiserEvent { get; set; }
        public virtual OrganiserRegister OrganiserRegister { get; set; }
    }
}
