//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganiserBankDetail
    {
        public string Username { get; set; }
        public int BankDetailId { get; set; }
        public string AccountHolderName { get; set; }
        public string BankName { get; set; }
        public Nullable<int> AccountNo { get; set; }
        public string Ifsc { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual OrganiserRegister OrganiserRegister { get; set; }
    }
}
