//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganiserSale
    {
        public int SalesId { get; set; }
        public string Username { get; set; }
        public string AffiliateLinkId { get; set; }
        public int EventId { get; set; }
        public string CustomerName { get; set; }
        public string EmailId { get; set; }
        public string PhoneNo { get; set; }
        public string TicketSold { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> Earnings { get; set; }
        public string TransactionNo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual OrganiserEvent OrganiserEvent { get; set; }
        public virtual OrganiserRegister OrganiserRegister { get; set; }
    }
}
