//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganiserEventCategory
    {
        public int EventId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int EventCategoryId { get; set; }
    
        public virtual OrganiserCategory OrganiserCategory { get; set; }
        public virtual OrganiserEvent OrganiserEvent { get; set; }
    }
}
