//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganiserReview
    {
        public string EmailId { get; set; }
        public int ReviewId { get; set; }
        public string Review { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string Status { get; set; }
        public int EventId { get; set; }
    
        public virtual OrganiserEvent OrganiserEvent { get; set; }
        public virtual UserRegister UserRegister { get; set; }
    }
}
