//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCorporate
    {
        public int CorporateId { get; set; }
        public string FullName { get; set; }
        public string TeamSize { get; set; }
        public string EmailId { get; set; }
        public string PhoneNo { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
