//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserView
    {
        public int ViewId { get; set; }
        public string EmailId { get; set; }
        public string AffiliateLinkId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual AffiliateRegister AffiliateRegister { get; set; }
    }
}
