//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEAffiliate
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLike
    {
        public int LikeId { get; set; }
        public string EmailId { get; set; }
        public int EventId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual OrganiserEvent OrganiserEvent { get; set; }
        public virtual UserRegister UserRegister { get; set; }
    }
}
